### ISSUE TITLE
data directory

### ISSUE THREAD

**Issue by JasonRafeMiller** [fbabd/bioactivity-against-SARS-CoV-2#1]
Could you add the data directory containing the files that are required by the notebooks in this repo? Thank you.

The files called bioactivity_data_preprocessed_CHEMBL* get downloaded by one of the notebooks, but their contents do not match what is shown in the publication, presumably because the ChEMBL database has been updated.

The files ChEMBL_data_all_PaDEL.csv and CheMBL_data_all_lipinski.csv each serve as the inputs to one notebook, but those files must be generated with 3rd party software, it seems.

**Comment by fbabd** [comment]
I have added a link in the data.md file that contains the data file used in the notebooks.

**Comment by JasonRafeMiller** [comment]
Thank you for your quick response! With the files you linked to, both notebooks have run to completion for me, so you may close the case. Thanks again.

In case it helps, I'll note that I needed to make 4 minor code modifications to keep up with changes in the imported Python packages. In the classification_padel notebook...

1. LazyClassifier must now be imported from lazypredict.Supervised. Also, one line in this package must be changed to keep up with scikit-learn: in Supervised.py, the ‘sparse’ parameter to the OneHotEncoder constructor should be removed or renamed sparse_output.
2. In the baseModel function, the hidden1 input shape must now be type tuple. This is accomplished by adding the parentheses and comma: (input_data.shape[1],). 
3. In the prepare_targets function, importing to_categorical() from np_utils no longer works. It works to execute ‘from keras import utils’ and then call utils.to_categorical().
4. In the callback_list, the model filename is now required to end in ‘.keras’ not ‘.h5’. Also, in subsequent code that plots the results, the hardcoded filename (ending in .h5) must be changed to match the actual output filename.
